name: hyoga-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cartopy
  - ipython
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - scipy
  - sphinx
  - sphinx-gallery
  - sphinx-autosummary-accessors
  - xarray
