name: hyoga-docs
channels:
  - conda-forge
dependencies:
  - python
  - cartopy
  - contextily
  - cf_xarray
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - scipy
  - sphinx
  - sphinx-autosummary-accessors
  - sphinx-book-theme>=0.3.3
  - sphinx-gallery
  - xarray
