name: hyoga-docs
channels:
  - conda-forge
dependencies:
  - python
  - cartopy
  - cf_xarray
  - ipython
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - scipy
  - sphinx
  - sphinx-autosummary-accessors
  - sphinx-book-theme
  - sphinx-gallery
  - xarray
